# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 4, 3, 8, 38, 780000, tzinfo=utc), verbose_name='\u53d1\u8868\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
