# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u4e8b\u4ef6', 'verbose_name_plural': '\u4e8b\u4ef6'},
        ),
        migrations.AddField(
            model_name='column',
            name='home_display',
            field=models.BooleanField(default=False, verbose_name='\u9996\u9875\u663e\u793a'),
        ),
        migrations.AddField(
            model_name='column',
            name='nav_display',
            field=models.BooleanField(default=False, verbose_name='\u5bfc\u822a\u663e\u793a'),
        ),
        migrations.AddField(
            model_name='event',
            name='abstract',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u5730\u70b9'),
        ),
        migrations.AddField(
            model_name='event',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u53d1\u8868\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u5609\u5bbe'),
        ),
        migrations.AddField(
            model_name='event',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='event',
            name='vis_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u8bbf\u95ee\u6b21\u6570'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(db_index=True, default='event', max_length=256, verbose_name='\u7f51\u5740'),
        ),
    ]
