# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20161104_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pub_date',
            new_name='pub_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='upd_date',
            new_name='upd_time',
        ),
    ]
