# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161104_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=256, verbose_name='auth.User'),
        ),
    ]
