# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20161104_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u4f5c\u8005'),
        ),
    ]
