# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161107_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='nav_display',
            field=models.BooleanField(default=False, verbose_name='\u5bfc\u822a\u663e\u793a'),
        ),
    ]
