# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 07:32
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20161107_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(null=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u5730\u70b9'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u5609\u5bbe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(db_index=True, default='event', max_length=256, verbose_name='\u7f51\u5740'),
        ),
    ]
