# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20161115_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u4e8b\u4ef6', 'verbose_name_plural': '\u4e8b\u4ef6'},
        ),
        migrations.AddField(
            model_name='event',
            name='vis_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u8bbf\u95ee\u6b21\u6570'),
        ),
    ]
